export const DESCRIPTIONS = [
  "lorem ipsum dolor sit amet",
  "consectetur [adipiscing elit",
  "sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
  "ut enim ad minim veniam",
  "quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
  "duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
  "excepteur sint occaecat cupidatat non proident",
  "sunt in culpa qui officia deserunt mollit anim id est laborum"
];

export const TITLES = [
  [
    "Key",
    "Top",
    "Main",
    "Chief",
    "Assistant to",
    "Advisory to",
    "Personal Assistant to",
    "Part Time",
  ],
  [
    "Senior",
    "Junior",
    "Regional",
    "Country",
    "Associate",
    "Head",
    "Super",
    "Local",
    "Global",
    "Assistant",
    "Independent",
    "Full-time",
    "Division",
    "National",
    "Creative",
    "Dedicated",
    "Operations",
    "Improvement",
    "Area",
    "Licenced",
    "Retail",
    "Office",
    "Industrial",
    "International"
  ],
  [
    "Development",
    "Technical",
    "Business",
    "Financial",
    "IT",
    "Project",
    "Cost",
    "Managing",
    "Commercial",
    "Procurement",
    "Cleaning",
    "Team",
    "Real Estate",
    "Sales",
    "Property",
    "Asset",
    "Facility",
    "Cashflow",
    "Creative",
    "Operation",
    "Letting",
    "Enterprise",
    "Corporate",
    "Accounting",
    "Green Building",
    "Construction",
    "Marketing",
    "Investment",
    "Customer",
    "Support",
    "Feedback"
  ]
];